apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:  # tutaj może być albo plik (yaml) albo key-pair czyli nazwa wartość
  appUrl: "http://my-app-service"
  timeout: "30"  # bierzemy tą wartość i ładujemy ją w configMapKeyRef poniżej.
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    env:
    - name: "request.timeout" # Env variable ...
      valueFrom:  # ...from
        configMapKeyRef:
          name: app-properties
          key: timeout
    - name: "application.url" # Env variable ...
      valueFrom:  # ...from
        configMapKeyRef:
          name: app-properties
          key: appUrl
    args:
    - env     # tylko do przetestowania czy działa, wywoła wartości w logach
