apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:  # tutaj może być albo plik (yaml) albo key-pair czyli nazwa wartość
  appUrl: "http://my-app-service"
  timeout: "30"  # bierzemy wszystkie wartości z tej sekcji i ładujemy je w configMapKeyRef poniżej.
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    envFrom:
    - configMapRef:
        name: app-properties
    args:
    - env     # tylko do przetestowania czy działa, wywoła wartości w logach
